/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sxau_soft_andsix_thread_LogoutThread */

#ifndef _Included_com_sxau_soft_andsix_thread_LogoutThread
#define _Included_com_sxau_soft_andsix_thread_LogoutThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sxau_soft_andsix_thread_LogoutThread_MIN_PRIORITY
#define com_sxau_soft_andsix_thread_LogoutThread_MIN_PRIORITY 1L
#undef com_sxau_soft_andsix_thread_LogoutThread_NORM_PRIORITY
#define com_sxau_soft_andsix_thread_LogoutThread_NORM_PRIORITY 5L
#undef com_sxau_soft_andsix_thread_LogoutThread_MAX_PRIORITY
#define com_sxau_soft_andsix_thread_LogoutThread_MAX_PRIORITY 10L
/*
 * Class:     com_sxau_soft_andsix_thread_LogoutThread
 * Method:    nativerun0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sxau_soft_andsix_thread_LogoutThread_nativerun0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
