/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yfdc_Test */

#ifndef _Included_yfdc_Test
#define _Included_yfdc_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yfdc_Test
 * Method:    sleep1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yfdc_Test_sleep1
  (JNIEnv *, jclass);

/*
 * Class:     yfdc_Test
 * Method:    native1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yfdc_Test_native1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
